---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  tags: apt


- name: Install some dev tools packages
  apt: pkg="{{item}}" state=latest
  become: yes
  tags: apt
  with_items:
    - vim-nox
    - htop

# TODO basic vimrc with python plugins?
